---
- name: Install and configure ollama and openwebui
  hosts:
    - all
  vars:
    _fqdn: "{{ workspace_fqdn | default('localhost:8080') }}" # workspace_fqdn is a special component parameter defined in SRC
    _openwebui_url: "{{ _fqdn is match 'localhost:' | ternary('http://', 'https://') }}{{ _fqdn }}"
  gather_facts: true
  pre_tasks:
    - ansible.builtin.package:
        name: libnginx-mod-http-lua
        state: present
  roles:
    - role: ollama-serve
      vars:
        ollama_serve_model: "{{ model }}"
        ollama_serve_version: "{{ ollama_version | default('') }}"
        ollama_serve_use_external_storage: "{{ ollama_use_external_storage | default(true, true) | bool }}"
    - role: openwebui
      vars:
        openwebui_url: "{{ _openwebui_url }}"
        openwebui_port: 8080
    - role: uusrc.general.nginx_reverse_proxy
      vars:
        nginx_reverse_proxy_locations:
          - name: openwebui
            location: /
            auth: sram
            proxy_pass: http://localhost:8080
            proxy_set_header:
              X-Remote-User-Mail: $username@localhost
            rewrite_by_lua_block: |
              {
                  local roles = ngx.var.src_roles or ""
                  -- Add leading/trailing semicolons to ensure exact matching of whole roles
                  local padded = ";" .. roles .. ";"
              
                  if padded:find(";src_co_admin;", 1, true) then
                      ngx.var.remote_role = "admin"
                  else
                      ngx.var.remote_role = "user"
                  end
              }
            proxy_set_header:
              X-Remote-Role: "$remote_role"
          - name: api
            location: /ext/api/ # serve the api under a special route to connect to it directly (instead of via the UI)
            auth: "{{ expose_api | default(true, true) | bool | ternary('noauth', 'sram') }}"
            proxy_pass: http://localhost:8080/api/
            proxy_set_header:
              X-Remote-User-Mail: '""' # ensure outside clients cannot set a trusted header
