- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Wait until api is up
      ansible.builtin.uri:
        url: http://localhost:80/ext/api/version
        follow_redirects: true
        url_username: foo
        url_password: bar
      register: wait_for_api
      until: "wait_for_api.status == 200"
      retries: 10
      delay: 5 # check every 5 seconds for a maximum of 5 minutes

    - name: Test api without basic auth
      ansible.builtin.uri:
        url: http://localhost:80/ext/api/version
        follow_redirects: true
        status_code: 401
