- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Test app with and without auth
      ansible.builtin.uri:
        url: http://localhost:8080/api/v1/auths/signin
        method: POST
        status_code: "{{ item.expected }}"
        follow_redirects: true
        body_format: json
        body:
          email: ""
          password: ""
        headers: "{{ item.headers | default(omit) }}"
      with_items:
        - headers:
            X-Remote-User-Mail: testuser
          expected: 200
        - expected: 400 # bad request in case no trusted header is set
