- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Ensure API redirects to SRAM
      ansible.builtin.uri:
        url: "http://localhost:80/ext/api/version"
        follow_redirects: none
        status_code: 302
      register: openwebui_service_live
      until: "openwebui_service_live.status == 302"
      retries: 10
      delay: 5

    - name: Test app without auth
      ansible.builtin.uri:
        url: http://localhost:8080/api/v1/auths/signin
        method: POST
        follow_redirects: true
        body_format: json
        status_code: 400
        body:
          email: ""
          password: ""
      retries: 10
      delay: 5
  
    - name: Test app with auth
      ansible.builtin.uri:
        url: http://localhost:8080/api/v1/auths/signin
        method: POST
        follow_redirects: true
        body_format: json
        body:
          email: ""
          password: ""
        headers:
            X-Remote-User-Mail: testuser
