---
driver:
  name: ${DRIVER-podman}
  image_settings: &image_settings
    pre_build_image: true
    registry:
      url: $DOCKER_REGISTRY
      credentials:
        username: $DOCKER_USER
        password: $DOCKER_PW
platforms: # Test on ubuntu jammy by default
  - name: workspace-src-ubuntu_jammy
    image: ghcr.io/utrechtuniversity/src-test-workspace:ubuntu_jammy
    command: /sbin/init
    <<: *image_settings
provisioner:
  name: ansible
  env:
    components:
      - name: test_component
        path: playbook.yml
        parameters:
          model: smollm:135m
