#SPDX-License-Identifier: MIT-0
---
# defaults file for ollama-serve
ollama_serve_model_base_dir: /opt/
ollama_serve_use_external_storage: true
ollama_serve_env:
  OLLAMA_FLASH_ATTENTION: "1"
  OLLAMA_MODELS: "{{ ollama_serve_model_storage_path }}"
ollama_serve_model: ""
ollama_serve_version: "" # latest by default
