#SPDX-License-Identifier: MIT-0
---
# tasks file for ollama-serve

- name: ollama user
  ansible.builtin.user:
    name: ollama
    system: true
    create_home: true

- name: Create ollama dir and model dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: ollama
    group: ollama
    mode: "0755"
  with_items:
    - /opt/ollama
    - "{{ ollama_serve_model_storage_path }}" # can be different from /opt/ollama if external storage is used

- name: Install zstd for unarchiving # ollama is served as a zstd file, Ansible's unarchive module depends on this package.
  ansible.builtin.package:
    name: zstd
    state: present

- name: Fetch and unarchive ollama
  ansible.builtin.unarchive:
    src: "{{ ollama_serve_tarball }}"
    remote_src: true
    dest: /opt/ollama
    creates: /opt/ollama/bin/ollama

- name: Place systemd config file
  notify: Reload and run ollama service
  ansible.builtin.template:
    dest: /etc/systemd/system/ollama-serve.service
    src: templates/ollama-serve.service.j2
    mode: "0644"

- name: Ensure ollama service is running
  ansible.builtin.systemd:
    name: ollama-serve
    state: started
    enabled: true

- name: Pull requested model
  tags: molecule-idempotence-notest
  ansible.builtin.command:
    cmd: /opt/ollama/bin/ollama pull "{{ ollama_serve_model }}"
  when: ollama_serve_model | length > 0
  delay: 10
